return {
  -- {
  --
  --   "mfussenegger/nvim-lint",
  --   config = function()
  --     require("lint").linters_by_ft = {
  --       lua = { "luacheck" },
  --       javascript = { "eslint_d" },
  --       typescript = { "eslint_d" },
  --       svelte = { "eslint_d" },
  --       json = { "jsonlint" },
  --       go = { "golangcilint" },
  --       rust = { "clippy" }
  --     }
  --
  --     vim.api.nvim_create_autocmd({ "BufEnter", "BufWritePost", "InsertLeave" }, {
  --       callback = function()
  --         require("lint").try_lint()
  --       end,
  --     })
  --
  --     -- vim.keymap.set("n", "<leader>ll", function()
  --     --   lint.try_lint()
  --     -- end, { desc = "Trigger linting for current file" })
  --   end,
  -- }
}
